# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle

name: Machinery components integration tests  build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: 'recursive'

    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Verify with Gradle
      run: ./gradlew test

    - name: Cache local Maven repository
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Publish machinery modules to maven local repository
      run:  ./gradlew :machinery-bom:publishAllToMavenLocal

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Verify with Maven
      run: ./mvnw -B verify --file pom.xml