# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle

name: Machinery components integration tests  build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Verify with Gradle
      run: ./gradlew test
